# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "build for testing using scan"
  lane :build_for_testing do
    scan(
      build_for_testing: true,
      clean: true
      )
  end

    desc "run tests using last build"
  lane :run_tests do
    scan(
      skip_build: true
      )
  end

  desc "clean, build and run tests"
  lane :build_and_test do
    build_for_testing
    run_tests
  end

end
